version: "3"
services:
  api_dev:
    image: arturnilson/api-ts
    ports:
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
  redis:
    image: "redis"